name: " Documentaci贸n"
description: "Template para tareas de documentaci贸n"
title: "[DOCS]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "##  Actualizaci贸n o creaci贸n de documentaci贸n"

  - type: textarea
    id: descripcion
    attributes:
      label: " Descripci贸n"
      description: "驴Qu茅 documento se va a crear o actualizar?"
      placeholder: "Actualizar README del microservicio X..."
    validations:
      required: true

  - type: textarea
    id: alcance
    attributes:
      label: " Alcance"
      description: "驴Qu茅 se incluir谩 en la documentaci贸n?"
      placeholder: "Diagramas, pasos de instalaci贸n, API reference..."
